sudo: required

services:
  - docker

before_install:
  - docker run --rm --privileged -v /:/host solita/ubuntu-systemd:16.04 setup
  - docker build -t morph1904/tygercaddy:16.04-test . -f travis/docker/Dockerfile
  - docker run -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG -e TRAVIS_COMMIT=$TRAVIS_COMMIT --name=tygertest --security-opt seccomp=unconfined -t -p 80:80 -p 443:443 -p 9090:9090 -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock morph1904/tygercaddy:16.04-test
  - docker start tygertest

script:
  - bash travis/script/response.sh
